/*
 *    Constellation - An open source and standard compliant SDI
 *    http://www.constellation-sdi.org
 *
 * Copyright 2014 Geomatys.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.constellation.sos.io.internal;

import java.io.StringWriter;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import org.apache.sis.storage.DataStoreException;

import org.apache.sis.xml.MarshallerPool;

import org.constellation.admin.SpringHelper;

import static org.constellation.api.CommonConstants.SENSOR_ID_BASE;
import org.constellation.business.IInternalSensorBusiness;
import org.geotoolkit.sensor.SensorWriter;
import org.geotoolkit.sml.xml.AbstractSensorML;
import org.geotoolkit.sml.xml.SensorMLMarshallerPool;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * A sensorML Writer working on a fileSystem.
 *
 * @author Guilhem Legal (Geomatys)
 */
public class InternalSensorWriter implements SensorWriter {

    /**
     * use for debugging purpose
     */
    protected static final Logger LOGGER = Logger.getLogger("org.constellation.sos.io.internal");

    @Autowired
    private IInternalSensorBusiness sensorBusiness;
    
    /**
     * A JAXB unmarshaller used to unmarshall the xml generated by the XMLWriter.
     */
    private final MarshallerPool marshallerPool;

    /**
     * The base identifier of all the sensor.
     */
    private final String sensorIdBase;

    public InternalSensorWriter(final Map<String, Object> properties) throws DataStoreException {
        SpringHelper.injectDependencies(this);
        this.sensorIdBase = (String) properties.get(SENSOR_ID_BASE);
        this.marshallerPool =  SensorMLMarshallerPool.getInstance();
        if (marshallerPool == null) {
            throw new DataStoreException("Unable to initialize the InternalSensorWriter JAXB context");
        }

    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean writeSensor(String id, final AbstractSensorML sensor) throws DataStoreException {
        try {
            final Marshaller marshaller = marshallerPool.acquireMarshaller();
            final StringWriter sw = new StringWriter();
            marshaller.marshal(sensor, sw);
            marshallerPool.recycle(marshaller);
            sensorBusiness.updateSensorMetadata(id, sw.toString());

        } catch (JAXBException ex) {
            String msg = ex.getMessage();
            if (msg == null && ex.getCause() != null) {
                msg = ex.getCause().getMessage();
            }
            throw new DataStoreException("the service has throw a JAXB Exception:" + msg, ex);
        }
        return true;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean deleteSensor(String id) {
        if (sensorBusiness.existSensor(id)) {
            sensorBusiness.delete(id);
            return true;
        } else {
            LOGGER.log(Level.WARNING, "unable to find a sensor {0} to remove", id);
            return false;
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int replaceSensor(String id, final AbstractSensorML sml) throws DataStoreException {
        try {
            if (sensorBusiness.existSensor(id)) {
                final Marshaller marshaller = marshallerPool.acquireMarshaller();
                final StringWriter sw = new StringWriter();
                marshaller.marshal(sml, sw);
                marshallerPool.recycle(marshaller);
                sensorBusiness.updateSensorMetadata(id, sw.toString());
            }
            return 1;
        } catch (JAXBException ex) {
            String msg = ex.getMessage();
            if (msg == null && ex.getCause() != null) {
                msg = ex.getCause().getMessage();
            }
            throw new DataStoreException("the service has throw a JAXB Exception:" + msg, ex);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getNewSensorId() throws DataStoreException {
        int maxID = 0;
        
        for (String id : sensorBusiness.getInternalSensorIds()) {
            if (id.startsWith(sensorIdBase)) {
                id = id.substring(id.indexOf(sensorIdBase) + sensorIdBase.length());
                try {
                    final int curentID = Integer.parseInt(id);
                    if (curentID > maxID) {
                        maxID = curentID;
                    }
                } catch (NumberFormatException ex) {
                    throw new DataStoreException("unable to parse the identifier:" + id, ex);
                }
            }
        } 
        
        return sensorIdBase + maxID + 1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void destroy() {
        
    }
}
