cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .m2
image: maven:latest
variables:
  MAVEN_USER: 'deployment'
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2'
  SONAR_TOKEN: '898841f3511b763fcdb4c6d1e5911baf6d999939'
  SONAR_HOST_URL: 'https://sonardev.geomatys.com'
  GIT_DEPTH: 0

stages:
  - build-examind-community
  - sonarqube
  - push

build:examind-community:
  only:
    refs:
      - master
  image: maven:3-jdk-8
  stage: build-examind-community
  script:
    - mvn clean install -DskipTests $MAVEN_CLI_OPTS -s $SETTINGS_MAVEN
  artifacts:
    paths:
      - modules/bundles/exa-bundle/target/

sonarqube-check:
  stage: sonarqube
  script:
    - mvn  sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL
  allow_failure: true
  only:
    - merge_requests
    - master

docker:push:
  image: docker:latest
  stage: push
  only:
    refs:
      - master
  script:
    # Login to Docker repository
    - mkdir ~/.docker && echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    # Move Examind .war next to Dockerfile
    - cp ./modules/bundles/exa-bundle/target/examind.war ./docker/mount/examind/tomcat/webapps/.
    # Build and push
    - docker build -t images.geomatys.com/examind/examind-community:latest ./docker/
    - docker push images.geomatys.com/examind/examind-community:latest
  artifacts:
    paths:
      - modules/bundles/exa-bundle/target/
