# IMPORTANT notes:
# 1. Use a global maven cache to avoid downloading released dependencies everytime
# 2. sis-migration disabled (see comments in .gitlab/CI/build.yml file)
# 3. Release stage not ready yet. Only a manual maven artifact is available for now. More details about release work in
#    "TODO" comment in related file.
variables:
  MAVEN_LOCAL: ".m2_local"
  MAVEN_OPTS: "-Dmaven.repo.local=$MAVEN_LOCAL -Djava.awt.headless=true"
  SONAR_HOST_URL: "https://sonar.geomatys.com"
  DEPLOY_SERVER: "releases::https://nexus.geomatys.com/repository/releases/"

# Cache dependencies globally. Project snapshot are removed with below after script to avoid caching nightly artifact.
cache: &global_cache
  policy: pull
  key: GLOBAL_MVN_CACHE # If needed, replace with CI_COMMIT_REF_SLUG for a per-branch cache.
  paths:
    - "$MAVEN_LOCAL"

stages:
  - build
  - test
  - quality
#  - release
  - publish

# Cannot use newer version of maven because we still need http repositories (Ex: http://jaspersoft.jfrog.io/jaspersoft)
image: maven:3.9.9-eclipse-temurin-23

# Force removing artifacts installed by local jobs, to avoid cache corruption with snapshots.
after_script:
  - mvn build-helper:remove-project-artifact > /dev/null && echo "Successfully removed project artifacts from cache"

# Hidden job to be inherited (extends) by build job
.update-cache:
  cache:
    <<: *global_cache
    policy: pull-push

# TODO: factorize betwween projects using a common Gitlab template.
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^project/

include:
  - '.gitlab/CI/build.yml'
  - '.gitlab/CI/test.yml'
  - '.gitlab/CI/quality.yml'
#  - '.gitlab/CI/release.yml'
  - '.gitlab/CI/publish.yml'
