postgresql:
  enabled: false

externalDatabase:
  # Values to use to reach database
  host: "my-domain"
  port: 5433
  database: "my-db"
  # Reference secret holding database username and password
  existingSecret: "my-db-credentials"
  existingSecretUserKey: "PG_USER"
  existingSecretPasswordKey: "PG_PASSWORD"
