apiVersion: v2
name: examind-community
description: |
  Deploys a stand-alone version of GIS server Examind.
  Deploys community edition by default. 
  If you are a paid customer, use `edition: server` value to deploy a complete edition.
type: application
home: https://www.examind.com
version: "1.0.0"
appVersion: "1.x"

maintainers:
  - name: Geomatys developer team
    email: contact@geomatys.com
    url: https://www.geomatys.com

sources:
  - https://github.com/geomatys/examind-community

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.27.0
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.5.6
    condition: postgresql.enabled
