= Examind Helm chart

Deploys a standalone Examind Community instance.

This chart is based on https://github.com/bitnami/charts/tree/main/template[Bitnami helm chart template].

== Configuration

=== Database

By default, this chart deploys a PostgreSQL database.
The database is deployed using https://github.com/bitnami/charts/tree/main/bitnami/postgresql[Bitnami PostgreSQL chart].
It is configurable under `postgresql` values.

==== Add Timescale and PostGIS capabilities

By default, Examind only store administration data (registered layers, created services, etc.) in its database, and a standard PostgreSQL is deployed.

However, Examind is capable to consume GIS data from a *PostGIS* database, and to use *TimeScaleDB* time-series capabilities to optimize sensor data processing.
To prepare a database with such capabilities, we can override deployed *PostgreSQL* configuration to create a secondary database with *TimescaleDB* and *PostGIS* extensions.

Example:

[source,yaml]
.values.yaml
----
include::../examples/personalize-deployment/values-deploy-timescale-postgis.yaml[]
----
<.> Allow insecure images: it is required to use *TimescaleDB* image instead of standard Bitnami image
<.> IMPORTANT: The *TimescaleDB* image must be compatible with *Bitnami*, so we must pull the Bitnami flavor (using `-bitnami` suffixed tags)
<.> Use a custom initialization script to create a data dedicated database (in this example, we name it `gis_data`) with both *TimescaleDB* and *PostGIS* extensions.
<.> Avoid using `asap_smooth` function, not available in used TimescaleDB edition

[WARNING]
====
This method does **not** include *timescaledb_toolkit*, and therefore does not support advanced functions like *asap_smooth*.
If you require timescaledb toolkit, you either have to deploy your own database and <<_use_external_database>>, or craft a PostgreSQL Docker image compatible with both TimescaleDB and Bitnami yourself.
====

[[_use_external_database]]
==== Use an external database

To use your own database instead, change values as follows:

. Disable embedded postgresql deployment:
+
[source,yaml]
.values.yaml
----
postgresql:
  enabled: false
----
. Setup database connection information using `externalDatabase` values:
+
[source,yaml]
.values.yaml
----
include::values.yaml[tag=externalDatabaseValues]
----
+
Examples:
+
.. Providing credentials inline:
+
[source,yaml]
.values.yaml
----
include::../examples/use-external-database/values.yaml[]
----
.. Referencing a secret holding database login and password:
+
[source,yaml]
.values.yaml
----
include::../examples/use-external-database/values-when-using-secret.yaml[]
----

=== Configure public URL

If Examind Ingress is enabled and specifies a list of hosts, the `CSTL_URL` variable will be infered from it. Examples:

* Using the following ingress, without `tls` configuration specified, produces the value `http://first.geomatys.com/examind`:
+
[source,yaml]
.values
----
include::../examples/public_url/values-infer-http-from-ingress.yaml[]
----
* if a `tls` configuration is set (either in global values or `allInOne` specific ingress configuration), then the value produced is `https://first.geomatys.com/examind`:
+
[source,yaml]
.values
----
include::../examples/public_url/values-infer-https-from-ingress.yaml[]
----

It is possible to set the `CSTL_URL` value manually through `allInOne.env.CSTL_URL` value. Example:

[source,yaml]
.values
----
include::../examples/public_url/values-override.yaml[]
----

=== Resource management

Examind CPU and memory resources can be configured using K8s resource configuration. Moreover, an additional `allInOne.heapSize` section must be set to fit JVM heap size according to Kubernetes memory reservation.

.Example:

[source,yaml]
.values.yaml
----
include::../examples/resources/values-resources-examind.yaml[]
----

When using internal database, its resources can also be configured through the `postgresql` subchart.
The subchart is based *Bitnami PostgreSQL helm chart*. For more information about resource configuration, https://github.com/bitnami/charts/tree/main/bitnami/postgresql#resource-requests-and-limits[see related documentation].

[source,yaml]
.values.yaml
----
include::../examples/resources/values-resources-postgresql.yaml[]
----

=== Switch edition

To switch from community (free) and server (paid) edition, you can set the `edition` value to `server`.
you also have to define an *image pull secret* to be able to download the paid edition from Geomatys private docker repository:

[source,yaml]
----
include::../examples/personalize-deployment/values-switch-edition.yaml[]
----

== Future improvements

* EPSG database configuration (for now, it uses the same database as Examind)
* Spring-Boot based deployment
* New UI deployment
