ALTER TABLE "admin"."metadata" DROP COLUMN "metadata_iso";

CREATE SEQUENCE "admin"."internal_metadata_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE;

CREATE TABLE "admin"."internal_metadata" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."internal_metadata_id_seq" NOT NULL,
    "metadata_id" character varying(100) NOT NULL,
    "metadata_iso" text NOT NULL
);

ALTER TABLE "admin"."internal_metadata" ADD CONSTRAINT internal_metadata_id_fk FOREIGN KEY ("id") REFERENCES "admin"."metadata" (id);
ALTER TABLE "admin"."internal_metadata" ADD CONSTRAINT internal_metadata_pk PRIMARY KEY ("id");

-- ALTER TABLE "internal_metadata" ALTER COLUMN "id" SET DEFAULT nextval('internal_metadata_id_seq'::regclass);