-- Add byte array field to store a attachements (used for metadata quicklook)

CREATE SEQUENCE "admin"."attachment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."attachment" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."attachment_id_seq" NOT NULL,
    "content" BLOB(500M) NOT NULL
);

--ALTER TABLE ONLY "admin"."attachment" ALTER COLUMN id SET DEFAULT nextval('admin.attachment_id_seq'::regclass);
ALTER TABLE ONLY "admin"."attachment" ADD CONSTRAINT attachment_pk PRIMARY KEY ("id");
