--
-- PostgreSQL database dump modified for hsql db
--
SET DATABASE SQL SYNTAX PGS TRUE;

--
-- TOC entry 7 (class 2615 OID 462067)
-- Name: admin; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA "admin";


CREATE SEQUENCE "admin"."chain_process_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."chain_process" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."chain_process_id_seq" NOT NULL,
    "auth" character varying(512),
    "code" character varying(512),
    "config" text
);


--
-- Name: crs; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."crs" (
    "dataid" integer NOT NULL,
    "crscode" character varying(64) NOT NULL
);


--
-- Name: cstl_user; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."cstl_user_id_seq"
    START WITH 2
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."cstl_user" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."cstl_user_id_seq" NOT NULL,
    "login" character varying(32) NOT NULL,
    "password" character varying(32) NOT NULL,
    "firstname" character varying(64) NOT NULL,
    "lastname" character varying(64) NOT NULL,
    "email" character varying(64) NOT NULL,
    "active" boolean NOT NULL,
    "avatar" character varying(64),
    "zip" character varying(64),
    "city" character varying(64),
    "country" character varying(64),
    "phone" character varying(64),
    "forgot_password_uuid" character varying(64),
    "address" text,
    "additional_address" text,
    "civility" character varying(64),
    "title" text,
    "locale" text NOT NULL
);



--
-- TOC entry 180 (class 1259 OID 462093)
-- Name: data; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."data_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."data" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."data_id_seq" NOT NULL,
    "name" character varying(512) NOT NULL,
    "namespace" character varying(256) NOT NULL,
    "provider" integer NOT NULL,
    "type" character varying(32) NOT NULL,
    "subtype" character varying(32) DEFAULT '' NOT NULL,
    "included" boolean DEFAULT true NOT NULL,
    "sensorable" boolean DEFAULT false NOT NULL,
    "date" bigint NOT NULL,
    "owner" integer,
    "metadata" text,
    "dataset_id" integer,
    "feature_catalog" text,
    "stats_result" text,
    "rendered" boolean,
    "stats_state" text,
    "hidden" boolean DEFAULT false NOT NULL
);


--
-- TOC entry 181 (class 1259 OID 462117)
-- Name: data_i18n; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."data_i18n" (
    "data_id" integer NOT NULL,
    "lang" character(2) NOT NULL,
    "title" integer NOT NULL,
    "description" integer NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 462719)
-- Name: data_x_data; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."data_x_data" (
    "data_id" integer NOT NULL,
    "child_id" integer NOT NULL
);


--
-- TOC entry 216 (class 1259 OID 462632)
-- Name: dataset; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."dataset_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."dataset" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."dataset_id_seq" NOT NULL,
    "identifier" character varying(100) NOT NULL,
    "owner" integer,
    "date" bigint,
    "feature_catalog" text
);



--
-- TOC entry 188 (class 1259 OID 462231)
-- Name: layer; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."layer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."layer" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."layer_id_seq" NOT NULL,
    "name" character varying(512) NOT NULL,
    "namespace" character varying(256),
    "alias" character varying(512),
    "service" integer NOT NULL,
    "data" integer NOT NULL,
    "date" bigint NOT NULL,
    "config" text,
    "owner" integer,
    "title" text
);


--
-- TOC entry 189 (class 1259 OID 462259)
-- Name: layer_i18n; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."layer_i18n" (
    "layer_id" integer  NOT NULL,
    "lang" character(2) NOT NULL,
    "title" integer NOT NULL,
    "description" integer NOT NULL
);

--
-- TOC entry 191 (class 1259 OID 462272)
-- Name: mapcontext; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."mapcontext_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."mapcontext" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."mapcontext_id_seq" NOT NULL,
    "name" character varying(512) NOT NULL,
    "owner" integer,
    "description" character varying(512),
    "crs" character varying(32),
    "west" double precision,
    "north" double precision,
    "east" double precision,
    "south" double precision,
    "keywords" character varying(256)
);


--
-- TOC entry 212 (class 1259 OID 462591)
-- Name: mapcontext_styled_layer; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."mapcontext_styled_layer_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."mapcontext_styled_layer" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."mapcontext_styled_layer_id_seq" NOT NULL,
    "mapcontext_id" integer NOT NULL,
    "layer_id" integer,
    "style_id" integer,
    "layer_order" integer DEFAULT 1 NOT NULL,
    "layer_opacity" integer DEFAULT 100 NOT NULL,
    "layer_visible" boolean DEFAULT true NOT NULL,
    "external_layer" character varying(512),
    "external_layer_extent" character varying(512),
    "external_service_url" character varying(512),
    "external_service_version" character varying(32),
    "external_style" character varying(128),
    "iswms" boolean DEFAULT true NOT NULL,
    "data_id" integer
);


--
-- TOC entry 219 (class 1259 OID 462774)
-- Name: metadata; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."metadata_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."metadata" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."metadata_id_seq" NOT NULL,
    "metadata_id" character varying(100) NOT NULL,
    "metadata_iso" text NOT NULL,
    "data_id" integer,
    "dataset_id" integer,
    "service_id" integer,
    "md_completion" integer,
    "owner" integer,
    "datestamp" bigint,
    "date_creation" bigint,
    "title" character varying(500),
    "profile" character varying(255),
    "parent_identifier" integer,
    "is_validated" boolean DEFAULT false NOT NULL,
    "is_published" boolean DEFAULT false NOT NULL,
    "level" character varying(50) DEFAULT 'NONE' NOT NULL,
    "resume" character varying(5000),
    "validation_required" character varying(10) DEFAULT 'NONE' NOT NULL,
    "validated_state" text,
    "comment" text
);


--
-- TOC entry 221 (class 1259 OID 462850)
-- Name: metadata_bbox; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."metadata_bbox" (
    "metadata_id" integer NOT NULL,
    "east" double precision NOT NULL,
    "west" double precision NOT NULL,
    "north" double precision NOT NULL,
    "south" double precision NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 462798)
-- Name: metadata_x_csw; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."metadata_x_csw" (
    "metadata_id" integer NOT NULL,
    "csw_id" integer NOT NULL
);


--
-- TOC entry 184 (class 1259 OID 462185)
-- Name: permission; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."permission_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."permission" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."permission_id_seq" NOT NULL,
    "name" character varying(32) NOT NULL,
    "description" character varying(512) NOT NULL
);



--
-- TOC entry 194 (class 1259 OID 462336)
-- Name: property; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."property" (
    "name" character varying(32) NOT NULL,
    "value" character varying(64) NOT NULL
);


--
-- TOC entry 178 (class 1259 OID 462080)
-- Name: provider; Type: TABLE; Schema: admin; Owner: -
--


CREATE SEQUENCE "admin"."provider_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."provider" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."provider_id_seq" NOT NULL,
    "identifier" character varying(512) NOT NULL,
    "parent" character varying(512),
    "type" character varying(8) NOT NULL,
    "impl" character varying(32) NOT NULL,
    "config" text NOT NULL,
    "owner" integer
);


--
-- TOC entry 205 (class 1259 OID 462520)
-- Name: role; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."role" (
    "name" character varying(32) NOT NULL
);


--
-- TOC entry 196 (class 1259 OID 462348)
-- Name: sensor; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."sensor_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."sensor" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."sensor_id_seq" NOT NULL,
    "identifier" character varying(512) NOT NULL,
    "type" character varying(64) NOT NULL,
    "parent" character varying(512),
    "owner" integer,
    "metadata" text,
    "date" bigint
);


--
-- TOC entry 197 (class 1259 OID 462364)
-- Name: sensored_data; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."sensored_data" (
    "sensor" integer NOT NULL,
    "data" integer NOT NULL
);


--
-- TOC entry 186 (class 1259 OID 462213)
-- Name: service; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."service_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;

CREATE TABLE "admin"."service" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."service_id_seq" NOT NULL,
    "identifier" character varying(512) NOT NULL,
    "type" character varying(32) NOT NULL,
    "date" bigint NOT NULL,
    "config" text,
    "owner" integer,
    "status" character varying(32) NOT NULL,
    "versions" character varying(32) NOT NULL
);


--
-- TOC entry 198 (class 1259 OID 462381)
-- Name: service_details; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."service_details" (
    "id" integer NOT NULL,
    "lang" character varying(3) NOT NULL,
    "content" text,
    "default_lang" boolean
);


--
-- TOC entry 199 (class 1259 OID 462395)
-- Name: service_extra_config; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."service_extra_config" (
    "id" integer NOT NULL,
    "filename" character varying(32) NOT NULL,
    "content" text
);


--
-- TOC entry 193 (class 1259 OID 462289)
-- Name: style; Type: TABLE; Schema: admin; Owner: -
--
CREATE SEQUENCE "admin"."style_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;


CREATE TABLE "admin"."style" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."style_id_seq" NOT NULL,
    "name" character varying(512) NOT NULL,
    "provider" integer NOT NULL,
    "type" character varying(32) NOT NULL,
    "date" bigint NOT NULL,
    "body" text NOT NULL,
    "owner" integer
);


--
-- TOC entry 200 (class 1259 OID 462424)
-- Name: style_i18n; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."style_i18n" (
    "style_id" integer NOT NULL,
    "lang" character(2) NOT NULL,
    "title" integer NOT NULL,
    "description" integer NOT NULL
);


--
-- TOC entry 201 (class 1259 OID 462452)
-- Name: styled_data; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."styled_data" (
    "style" integer NOT NULL,
    "data" integer NOT NULL
);


--
-- TOC entry 202 (class 1259 OID 462469)
-- Name: styled_layer; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."styled_layer" (
    "style" integer NOT NULL,
    "layer" integer NOT NULL,
    "is_default" boolean
);


--
-- TOC entry 203 (class 1259 OID 462486)
-- Name: task; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."task" (
    "identifier" character varying(512) NOT NULL,
    "state" character varying(32) NOT NULL,
    "type" character varying(32) NOT NULL,
    "date_start" bigint NOT NULL,
    "date_end" bigint,
    "owner" integer,
    "message" text,
    "task_parameter_id" integer,
    "progress" double precision,
    "task_output" text
);


--
-- TOC entry 204 (class 1259 OID 462500)
-- Name: task_i18n; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."task_i18n" (
    "task_identifier" character varying(512) NOT NULL,
    "lang" character(2) NOT NULL,
    "title" integer NOT NULL,
    "description" integer NOT NULL
);


--
-- TOC entry 214 (class 1259 OID 462620)
-- Name: task_parameter; Type: TABLE; Schema: admin; Owner: -
--

CREATE SEQUENCE "admin"."task_parameter_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE;



CREATE TABLE "admin"."task_parameter" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."task_parameter_id_seq" NOT NULL,
    "owner" integer NOT NULL,
    "name" character varying(255) NOT NULL,
    "date" bigint NOT NULL,
    "process_authority" character varying(100) NOT NULL,
    "process_code" character varying(100) NOT NULL,
    "inputs" text NOT NULL,
    "trigger" text,
    "trigger_type" character varying(30),
    "type" text
);


--
-- TOC entry 206 (class 1259 OID 462525)
-- Name: user_x_role; Type: TABLE; Schema: admin; Owner: -
--

CREATE TABLE "admin"."user_x_role" (
    "user_id" integer NOT NULL,
    "role" character varying(32) NOT NULL
);


--
-- TOC entry 2075 (class 2604 OID 462582)
-- Name: id; Type: DEFAULT; Schema: admin; Owner: -
--

--ALTER TABLE  "admin"."chain_process" ALTER COLUMN id SET DEFAULT nextval('chain_process_id_seq'::regclass);
--ALTER TABLE  "admin"."cstl_user" ALTER COLUMN id SET DEFAULT nextval('cstl_user_id_seq'::regclass);
--ALTER TABLE  "admin"."data" ALTER COLUMN id SET DEFAULT nextval('data_id_seq'::regclass);
--ALTER TABLE "admin"."dataset" ALTER COLUMN id SET DEFAULT nextval('dataset_id_seq'::regclass);
--ALTER TABLE "admin"."layer" ALTER COLUMN id SET DEFAULT nextval('layer_id_seq'::regclass);
--ALTER TABLE "admin"."mapcontext" ALTER COLUMN id SET DEFAULT nextval('mapcontext_id_seq'::regclass);
--ALTER TABLE "admin"."mapcontext_styled_layer" ALTER COLUMN id SET DEFAULT nextval('mapcontext_styled_layer_id_seq'::regclass);
--ALTER TABLE "admin"."metadata" ALTER COLUMN id SET DEFAULT nextval('metadata_id_seq'::regclass);
--ALTER TABLE "admin"."permission" ALTER COLUMN id SET DEFAULT nextval('permission_id_seq'::regclass);
--ALTER TABLE "admin"."provider" ALTER COLUMN id SET DEFAULT nextval('provider_id_seq'::regclass);
--ALTER TABLE "admin"."sensor" ALTER COLUMN id SET DEFAULT nextval('sensor_id_seq'::regclass);
--ALTER TABLE "admin"."service" ALTER COLUMN id SET DEFAULT nextval('service_id_seq'::regclass);
--ALTER TABLE  "admin"."style" ALTER COLUMN id SET DEFAULT nextval('style_id_seq'::regclass);
--ALTER TABLE  "admin"."task_parameter" ALTER COLUMN id SET DEFAULT nextval('task_parameter_id_seq'::regclass);

--
-- TOC entry 2358 (class 0 OID 462070)
-- Dependencies: 176
-- Data for Name: cstl_user; Type: TABLE DATA; Schema: admin; Owner: -
--

INSERT INTO "admin"."cstl_user" VALUES (1, 'admin', '21232f297a57a5a743894a0e4a801fc3', '', 'Administrator', 'contact@geomatys.com', true, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'en');


INSERT INTO "admin"."permission" VALUES (1, 'SERVICE_READ_ACCESS', 'Accès en lecture des service');
INSERT INTO "admin"."permission" VALUES (2, 'SERVICE_WRITE_ACCESS', 'Accès en écriture des service');
INSERT INTO "admin"."permission" VALUES (3, 'SERVICE_CREATION', 'Création de service');
INSERT INTO "admin"."permission" VALUES (4, 'DATA_CREATION', 'Création de donnée');

INSERT INTO "admin"."role" VALUES ('cstl-admin');
INSERT INTO "admin"."role" VALUES ('cstl-publish');
INSERT INTO "admin"."role" VALUES ('cstl-data');


INSERT INTO "admin"."user_x_role" VALUES (1, 'cstl-admin');


--
-- TOC entry 2185 (class 2606 OID 462587)
-- Name: chain_process_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."chain_process" ADD CONSTRAINT chain_process_pk PRIMARY KEY ("id");


--
-- TOC entry 2111 (class 2606 OID 462132)
-- Name: crs_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."crs"
    ADD CONSTRAINT crs_pk PRIMARY KEY ("dataid", "crscode");


--
-- TOC entry 2089 (class 2606 OID 462871)
-- Name: cstl_user_email_key; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."cstl_user"
    ADD CONSTRAINT cstl_user_email_key UNIQUE ("email");


--
-- TOC entry 2091 (class 2606 OID 462876)
-- Name: cstl_user_forgot_password_uuid_key; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."cstl_user"
    ADD CONSTRAINT cstl_user_forgot_password_uuid_key UNIQUE ("forgot_password_uuid");


--
-- TOC entry 2093 (class 2606 OID 462077)
-- Name: cstl_user_login_key; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."cstl_user"
    ADD CONSTRAINT cstl_user_login_key UNIQUE ("login");


--
-- TOC entry 2108 (class 2606 OID 462121)
-- Name: data_i18n_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."data_i18n"
    ADD CONSTRAINT data_i18n_pk PRIMARY KEY ("data_id", "lang");


--
-- TOC entry 2104 (class 2606 OID 462104)
-- Name: data_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."data"
    ADD CONSTRAINT data_pk PRIMARY KEY ("id");


--
-- TOC entry 2195 (class 2606 OID 462733)
-- Name: data_x_data_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."data_x_data"
    ADD CONSTRAINT data_x_data_pk PRIMARY KEY ("data_id", "child_id");


--
-- TOC entry 2193 (class 2606 OID 462640)
-- Name: dataset_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."dataset"
    ADD CONSTRAINT dataset_pk PRIMARY KEY ("id");


--
-- TOC entry 2130 (class 2606 OID 462263)
-- Name: layer_i18n_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."layer_i18n"
    ADD CONSTRAINT layer_i18n_pk PRIMARY KEY ("layer_id", "lang");


--
-- TOC entry 2123 (class 2606 OID 462708)
-- Name: layer_name_uq; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."layer"
    ADD CONSTRAINT layer_name_uq UNIQUE ("name", "namespace", "service");


--
-- TOC entry 2126 (class 2606 OID 462239)
-- Name: layer_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."layer"
    ADD CONSTRAINT layer_pk PRIMARY KEY ("id");


--
-- TOC entry 2133 (class 2606 OID 462280)
-- Name: mapcontext_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."mapcontext"
    ADD CONSTRAINT mapcontext_pk PRIMARY KEY ("id");


--
-- TOC entry 2187 (class 2606 OID 462602)
-- Name: mapcontext_styled_layer_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."mapcontext_styled_layer"
    ADD CONSTRAINT mapcontext_styled_layer_pk PRIMARY KEY ("id");


--
-- TOC entry 2201 (class 2606 OID 462859)
-- Name: metadata_bbox_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata_bbox"
    ADD CONSTRAINT metadata_bbox_pk PRIMARY KEY ("metadata_id", "east", "west", "north", "south");


--
-- TOC entry 2197 (class 2606 OID 462782)
-- Name: metadata_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata"
    ADD CONSTRAINT metadata_pk PRIMARY KEY ("id");


--
-- TOC entry 2199 (class 2606 OID 462802)
-- Name: metadata_x_csw_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata_x_csw"
    ADD CONSTRAINT metadata_x_csw_pk PRIMARY KEY ("metadata_id", "csw_id");


--
-- TOC entry 2113 (class 2606 OID 462193)
-- Name:"admin"."permission"_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."permission"
    ADD CONSTRAINT permission_pk PRIMARY KEY ("id");


--
-- TOC entry 2141 (class 2606 OID 462340)
-- Name: property_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."property"
    ADD CONSTRAINT property_pk PRIMARY KEY ("name");


--
-- TOC entry 2099 (class 2606 OID 462088)
-- Name: provider_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."provider"
    ADD CONSTRAINT provider_pk PRIMARY KEY ("id");


--
-- TOC entry 2176 (class 2606 OID 462524)
-- Name: role_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."role"
    ADD CONSTRAINT role_pk PRIMARY KEY ("name");


--
-- TOC entry 2150 (class 2606 OID 462368)
-- Name: sensor_data_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."sensored_data"
    ADD CONSTRAINT sensor_data_pk PRIMARY KEY ("sensor", "data");


--
-- TOC entry 2143 (class 2606 OID 462660)
-- Name: sensor_id_uq; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."sensor"
    ADD CONSTRAINT sensor_id_uq UNIQUE ("identifier");


--
-- TOC entry 2147 (class 2606 OID 462356)
-- Name: sensor_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."sensor"
    ADD CONSTRAINT sensor_pk PRIMARY KEY ("id");


--
-- TOC entry 2154 (class 2606 OID 462388)
-- Name: service_details_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."service_details"
    ADD CONSTRAINT service_details_pk PRIMARY KEY ("id", "lang");


--
-- TOC entry 2157 (class 2606 OID 462402)
-- Name: service_extra_config_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."service_extra_config"
    ADD CONSTRAINT service_extra_config_pk PRIMARY KEY ("id", "filename");


--
-- TOC entry 2117 (class 2606 OID 462221)
-- Name: service_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."service"
    ADD CONSTRAINT service_pk PRIMARY KEY ("id");


--
-- TOC entry 2119 (class 2606 OID 462562)
-- Name: service_uq; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."service"
    ADD CONSTRAINT service_uq UNIQUE ("identifier", "type");


--
-- TOC entry 2101 (class 2606 OID 462566)
-- Name: sql140711122144190; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."provider"
    ADD CONSTRAINT sql140711122144190 UNIQUE ("identifier");


--
-- TOC entry 2159 (class 2606 OID 462428)
-- Name: style_i18n_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."style_i18n"
    ADD CONSTRAINT style_i18n_pk PRIMARY KEY ("style_id", "lang");


--
-- TOC entry 2135 (class 2606 OID 462658)
-- Name: style_name_provider_uq; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."style"
    ADD CONSTRAINT style_name_provider_uq UNIQUE ("name", "provider");


--
-- TOC entry 2138 (class 2606 OID 462297)
-- Name: style_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."style"
    ADD CONSTRAINT style_pk PRIMARY KEY ("id");


--
-- TOC entry 2163 (class 2606 OID 462456)
-- Name: styled_data_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."styled_data"
    ADD CONSTRAINT styled_data_pk PRIMARY KEY ("style", "data");


--
-- TOC entry 2167 (class 2606 OID 462473)
-- Name: styled_layer_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."styled_layer"
    ADD CONSTRAINT styled_layer_pk PRIMARY KEY ("style", "layer");


--
-- TOC entry 2174 (class 2606 OID 462560)
-- Name: task_i18n_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."task_i18n"
    ADD CONSTRAINT task_i18n_pk PRIMARY KEY ("task_identifier", "lang");


--
-- TOC entry 2190 (class 2606 OID 462628)
-- Name: task_parameter_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."task_parameter"
    ADD CONSTRAINT task_parameter_pk PRIMARY KEY ("id");


--
-- TOC entry 2171 (class 2606 OID 462493)
-- Name: task_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."task"
    ADD CONSTRAINT task_pk PRIMARY KEY ("identifier");


--
-- TOC entry 2095 (class 2606 OID 462075)
-- Name: user_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."cstl_user"
    ADD CONSTRAINT user_pk PRIMARY KEY ("id");


--
-- TOC entry 2178 (class 2606 OID 462529)
-- Name: user_x_role_pk; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."user_x_role"
    ADD CONSTRAINT user_x_role_pk PRIMARY KEY ("user_id", "role");


--
-- TOC entry 2182 (class 2606 OID 462869)
-- Name: user_x_role_user_id_key; Type: CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."user_x_role"
    ADD CONSTRAINT user_x_role_user_id_key UNIQUE ("user_id");


--
-- TOC entry 2120 (class 1259 OID 462240)
-- Name: LAYER_NAME-SERVICE_IDX; Type: INDEX; Schema: admin; Owner: -
--

CREATE UNIQUE INDEX "LAYER_NAME-SERVICE_IDX" ON "admin"."layer"  ("name", "service");


--
-- TOC entry 2114 (class 1259 OID 462222)
-- Name: SERVICE_IDENTIFIER-TYPE_IDX; Type: INDEX; Schema: admin; Owner: -
--

CREATE UNIQUE INDEX "SERVICE_IDENTIFIER-TYPE_IDX" ON "admin"."service"  ("identifier", "type");


--
-- TOC entry 2183 (class 1259 OID 462588)
-- Name: chain_process_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE UNIQUE INDEX chain_process_idx ON "admin"."chain_process"  ("auth", "code");


--
-- TOC entry 2109 (class 1259 OID 462133)
-- Name: crs_dataid_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX crs_dataid_idx ON "admin"."crs"  ("dataid");


--
-- TOC entry 2106 (class 1259 OID 462122)
-- Name: data_i18n_data_id_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX data_i18n_data_id_idx ON "admin"."data_i18n"  ("data_id");


--
-- TOC entry 2102 (class 1259 OID 462105)
-- Name: data_owner_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX data_owner_idx ON "admin"."data"  ("owner");


--
-- TOC entry 2105 (class 1259 OID 462106)
-- Name: data_provider_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX data_provider_idx ON "admin"."data"  ("provider");


--
-- TOC entry 2191 (class 1259 OID 462651)
-- Name: dataset_owner_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX dataset_owner_idx ON "admin"."dataset"  ("owner");


--
-- TOC entry 2121 (class 1259 OID 462242)
-- Name: layer_data_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX layer_data_idx ON "admin"."layer"  ("data");


--
-- TOC entry 2128 (class 1259 OID 462264)
-- Name: layer_i18n_layer_id_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX layer_i18n_layer_id_idx ON "admin"."layer_i18n"  ("layer_id");


--
-- TOC entry 2124 (class 1259 OID 462243)
-- Name: layer_owner_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX layer_owner_idx ON "admin"."layer"  ("owner");


--
-- TOC entry 2127 (class 1259 OID 462241)
-- Name: layer_service_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX layer_service_idx ON "admin"."layer"  ("service");


--
-- TOC entry 2131 (class 1259 OID 462281)
-- Name: mapcontext_owner_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX mapcontext_owner_idx ON "admin"."mapcontext"  ("owner");


--
-- TOC entry 2096 (class 1259 OID 462089)
-- Name: provider_identifier_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE UNIQUE INDEX provider_identifier_idx ON "admin"."provider"  ("identifier");


--
-- TOC entry 2097 (class 1259 OID 462090)
-- Name: provider_owner_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX provider_owner_idx ON "admin"."provider"  ("owner");


--
-- TOC entry 2148 (class 1259 OID 462370)
-- Name: sensor_data_data_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX sensor_data_data_idx ON "admin"."sensored_data"  ("data");


--
-- TOC entry 2151 (class 1259 OID 462369)
-- Name: sensor_data_sensor_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX sensor_data_sensor_idx ON "admin"."sensored_data"  ("sensor");


--
-- TOC entry 2144 (class 1259 OID 462357)
-- Name: sensor_identifier_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE UNIQUE INDEX sensor_identifier_idx ON "admin"."sensor"  ("identifier");


--
-- TOC entry 2145 (class 1259 OID 462358)
-- Name: sensor_identifier_owner; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX sensor_identifier_owner ON "admin"."sensor"  ("owner");


--
-- TOC entry 2152 (class 1259 OID 462389)
-- Name: service_details_id_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX service_details_id_idx ON "admin"."service_details"  ("id");


--
-- TOC entry 2155 (class 1259 OID 462403)
-- Name: service_extra_config_id_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX service_extra_config_id_idx ON "admin"."service_extra_config"  ("id");


--
-- TOC entry 2115 (class 1259 OID 462223)
-- Name: service_owner_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX service_owner_idx ON "admin"."service"  ("owner");


--
-- TOC entry 2160 (class 1259 OID 462429)
-- Name: style_i18n_style_id_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX style_i18n_style_id_idx ON "admin"."style_i18n"  ("style_id");


--
-- TOC entry 2136 (class 1259 OID 462298)
-- Name: style_owner_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX style_owner_idx ON "admin"."style"  ("owner");


--
-- TOC entry 2139 (class 1259 OID 462299)
-- Name: style_provider_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX style_provider_idx ON "admin"."style"  ("provider");


--
-- TOC entry 2161 (class 1259 OID 462458)
-- Name: d_data_data_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX styled_data_data_idx ON "admin"."styled_data"  ("data");


--
-- TOC entry 2164 (class 1259 OID 462457)
-- Name: styled_data_style_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX styled_data_style_idx ON "admin"."styled_data"  ("style");


--
-- TOC entry 2165 (class 1259 OID 462475)
-- Name: styled_layer_layer_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX styled_layer_layer_idx ON "admin"."styled_layer"  ("layer");


--
-- TOC entry 2168 (class 1259 OID 462474)
-- Name: styled_layer_style_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX styled_layer_style_idx ON "admin"."styled_layer"  ("style");


--
-- TOC entry 2172 (class 1259 OID 462506)
-- Name: task_i18n_identifier_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX task_i18n_identifier_idx ON "admin"."task_i18n"  ("task_identifier");


--
-- TOC entry 2169 (class 1259 OID 462494)
-- Name: task_owner_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX task_owner_idx ON "admin"."task"  ("owner");


--
-- TOC entry 2188 (class 1259 OID 462629)
-- Name: task_parameter_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE UNIQUE INDEX task_parameter_idx ON "admin"."task_parameter"  ("name", "process_authority", "process_code");


--
-- TOC entry 2179 (class 1259 OID 462531)
-- Name: user_x_role_role_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX user_x_role_role_idx ON "admin"."user_x_role"  ("role");


--
-- TOC entry 2180 (class 1259 OID 462530)
-- Name: user_x_role_user_id_idx; Type: INDEX; Schema: admin; Owner: -
--

CREATE INDEX user_x_role_user_id_idx ON "admin"."user_x_role"  ("user_id");


--
-- TOC entry 2245 (class 2606 OID 462853)
-- Name: bbox_metadata_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata_bbox"
    ADD CONSTRAINT bbox_metadata_fk FOREIGN KEY ("metadata_id") REFERENCES "admin"."metadata"("id") ON DELETE CASCADE;


--
-- TOC entry 2207 (class 2606 OID 462134)
-- Name: crs_dataid_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."crs"
    ADD CONSTRAINT crs_dataid_fk FOREIGN KEY ("dataid") REFERENCES "admin"."data"("id") ON DELETE CASCADE;


--
-- TOC entry 2243 (class 2606 OID 462803)
-- Name: csw_metadata_cross_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata_x_csw"
    ADD CONSTRAINT csw_metadata_cross_id_fk FOREIGN KEY ("csw_id") REFERENCES "admin"."service"("id") ON DELETE CASCADE;


--
-- TOC entry 2205 (class 2606 OID 462646)
-- Name: data_dataset_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."data"
    ADD CONSTRAINT data_dataset_id_fk FOREIGN KEY ("dataset_id") REFERENCES "admin"."dataset"("id");


--
-- TOC entry 2206 (class 2606 OID 462123)
-- Name: data_i18n_data_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."data_i18n"
    ADD CONSTRAINT data_i18n_data_id_fk FOREIGN KEY ("data_id") REFERENCES "admin"."data"("id") ON DELETE CASCADE;


--
-- TOC entry 2203 (class 2606 OID 462107)
-- Name: data_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."data"
    ADD CONSTRAINT data_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2204 (class 2606 OID 462112)
-- Name: data_provider_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."data"
    ADD CONSTRAINT data_provider_fk FOREIGN KEY ("provider") REFERENCES "admin"."provider"("id") ON DELETE CASCADE;


--
-- TOC entry 2237 (class 2606 OID 462722)
-- Name: data_x_data_cross_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."data_x_data"
    ADD CONSTRAINT data_x_data_cross_id_fk FOREIGN KEY ("data_id") REFERENCES "admin"."data"("id") ON DELETE CASCADE;


--
-- TOC entry 2238 (class 2606 OID 462727)
-- Name: data_x_data_cross_id_fk2; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."data_x_data"
    ADD CONSTRAINT data_x_data_cross_id_fk2 FOREIGN KEY ("child_id") REFERENCES "admin"."data"("id") ON DELETE CASCADE;


--
-- TOC entry 2236 (class 2606 OID 462652)
-- Name: dataset_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."dataset"
    ADD CONSTRAINT dataset_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2211 (class 2606 OID 462254)
-- Name: layer_data_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."layer"
    ADD CONSTRAINT layer_data_fk FOREIGN KEY ("data") REFERENCES "admin"."data"("id") ON DELETE CASCADE;


--
-- TOC entry 2212 (class 2606 OID 462265)
-- Name: layer_i18n_layer_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."layer_i18n"
    ADD CONSTRAINT layer_i18n_layer_id_fk FOREIGN KEY ("layer_id") REFERENCES "admin"."layer"("id") ON DELETE CASCADE;


--
-- TOC entry 2209 (class 2606 OID 462244)
-- Name: layer_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."layer"
    ADD CONSTRAINT layer_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2210 (class 2606 OID 462249)
-- Name: layer_service_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."layer"
    ADD CONSTRAINT layer_service_fk FOREIGN KEY ("service") REFERENCES "admin"."service"("id") ON DELETE CASCADE;


--
-- TOC entry 2213 (class 2606 OID 462282)
-- Name: mapcontext_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."mapcontext"
    ADD CONSTRAINT mapcontext_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2235 (class 2606 OID 462742)
-- Name: mapcontext_styled_layer_data_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."mapcontext_styled_layer"
    ADD CONSTRAINT mapcontext_styled_layer_data_id_fk FOREIGN KEY ("data_id") REFERENCES "admin"."data"("id") ON DELETE CASCADE;


--
-- TOC entry 2233 (class 2606 OID 462608)
-- Name: mapcontext_styled_layer_layer_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."mapcontext_styled_layer"
    ADD CONSTRAINT mapcontext_styled_layer_layer_id_fk FOREIGN KEY ("layer_id") REFERENCES "admin"."layer"("id") ON DELETE CASCADE;


--
-- TOC entry 2232 (class 2606 OID 462603)
-- Name: mapcontext_styled_layer_mapcontext_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."mapcontext_styled_layer"
    ADD CONSTRAINT mapcontext_styled_layer_mapcontext_id_fk FOREIGN KEY ("mapcontext_id") REFERENCES "admin"."mapcontext"("id") ON DELETE CASCADE;


--
-- TOC entry 2234 (class 2606 OID 462613)
-- Name: mapcontext_styled_layer_style_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."mapcontext_styled_layer"
    ADD CONSTRAINT mapcontext_styled_layer_style_id_fk FOREIGN KEY ("style_id") REFERENCES "admin"."style"("id") ON DELETE CASCADE;


--
-- TOC entry 2244 (class 2606 OID 462808)
-- Name: metadata_csw_cross_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata_x_csw"
    ADD CONSTRAINT metadata_csw_cross_id_fk FOREIGN KEY ("metadata_id") REFERENCES "admin"."metadata"("id") ON DELETE CASCADE;


--
-- TOC entry 2239 (class 2606 OID 462783)
-- Name: metadata_data_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata"
    ADD CONSTRAINT metadata_data_fk FOREIGN KEY ("data_id") REFERENCES "admin"."data"("id") ON DELETE CASCADE;


--
-- TOC entry 2240 (class 2606 OID 462788)
-- Name: metadata_dataset_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata"
    ADD CONSTRAINT metadata_dataset_fk FOREIGN KEY ("dataset_id") REFERENCES "admin"."dataset"("id") ON DELETE CASCADE;


--
-- TOC entry 2242 (class 2606 OID 462837)
-- Name: metadata_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata"
    ADD CONSTRAINT metadata_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2241 (class 2606 OID 462793)
-- Name: metadata_service_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."metadata"
    ADD CONSTRAINT metadata_service_fk FOREIGN KEY ("service_id") REFERENCES "admin"."service"("id") ON DELETE CASCADE;


--
-- TOC entry 2202 (class 2606 OID 462341)
-- Name: provider_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."provider"
    ADD CONSTRAINT provider_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2216 (class 2606 OID 462359)
-- Name: sensor_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."sensor"
    ADD CONSTRAINT sensor_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2217 (class 2606 OID 462661)
-- Name: sensor_parent_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."sensor"
    ADD CONSTRAINT sensor_parent_fk FOREIGN KEY ("parent") REFERENCES "admin"."sensor"("identifier") ON DELETE CASCADE;


--
-- TOC entry 2219 (class 2606 OID 462376)
-- Name: sensored_data_data_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."sensored_data"
    ADD CONSTRAINT sensored_data_data_fk FOREIGN KEY ("data") REFERENCES "admin"."data"("id") ON DELETE CASCADE;


--
-- TOC entry 2218 (class 2606 OID 462371)
-- Name: sensored_data_sensor_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."sensored_data"
    ADD CONSTRAINT sensored_data_sensor_fk FOREIGN KEY ("sensor") REFERENCES "admin"."sensor"("id") ON DELETE CASCADE;


--
-- TOC entry 2220 (class 2606 OID 462390)
-- Name: service_details_service_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."service_details"
    ADD CONSTRAINT service_details_service_id_fk FOREIGN KEY ("id") REFERENCES "admin"."service"("id") ON DELETE CASCADE;


--
-- TOC entry 2221 (class 2606 OID 462404)
-- Name: service_extra_config_service_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."service_extra_config"
    ADD CONSTRAINT service_extra_config_service_id_fk FOREIGN KEY ("id") REFERENCES "admin"."service"("id") ON DELETE CASCADE;


--
-- TOC entry 2208 (class 2606 OID 462224)
-- Name: service_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."service"
    ADD CONSTRAINT service_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2222 (class 2606 OID 462430)
-- Name: style_i18n_style_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE "admin"."style_i18n"
    ADD CONSTRAINT style_i18n_style_id_fk FOREIGN KEY ("style_id") REFERENCES "admin"."style"("id") ON DELETE CASCADE;


--
-- TOC entry 2214 (class 2606 OID 462300)
-- Name: style_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."style"
    ADD CONSTRAINT style_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2215 (class 2606 OID 462305)
-- Name: style_provider_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."style"
    ADD CONSTRAINT "admin"."style_provider_fk" FOREIGN KEY ("provider") REFERENCES "admin"."provider"("id") ON DELETE CASCADE;


--
-- TOC entry 2224 (class 2606 OID 462464)
-- Name: styled_data_data_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."styled_data"
    ADD CONSTRAINT styled_data_data_fk FOREIGN KEY ("data") REFERENCES "admin"."data"("id") ON DELETE CASCADE;


--
-- TOC entry 2223 (class 2606 OID 462459)
-- Name: styled_data_style_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."styled_data"
    ADD CONSTRAINT styled_data_style_fk FOREIGN KEY ("style") REFERENCES "admin"."style"("id") ON DELETE CASCADE;


--
-- TOC entry 2226 (class 2606 OID 462481)
-- Name: styled_layer_layer_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."styled_layer"
    ADD CONSTRAINT styled_layer_layer_fk FOREIGN KEY ("layer") REFERENCES "admin"."layer"("id") ON DELETE CASCADE;


--
-- TOC entry 2225 (class 2606 OID 462476)
-- Name: styled_layer_style_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."styled_layer"
    ADD CONSTRAINT styled_layer_style_fk FOREIGN KEY ("style") REFERENCES "admin"."style"("id") ON DELETE CASCADE;


--
-- TOC entry 2229 (class 2606 OID 462507)
-- Name: task_i18n_task_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."task_i18n"
    ADD CONSTRAINT task_i18n_task_id_fk FOREIGN KEY ("task_identifier") REFERENCES "admin"."task"("identifier") ON DELETE CASCADE;


--
-- TOC entry 2227 (class 2606 OID 462495)
-- Name: task_owner_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."task"
    ADD CONSTRAINT task_owner_fk FOREIGN KEY ("owner") REFERENCES "admin"."cstl_user"("id");


--
-- TOC entry 2228 (class 2606 OID 462767)
-- Name: task_task_parameter_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."task"
    ADD CONSTRAINT task_task_parameter_id_fk FOREIGN KEY ("task_parameter_id") REFERENCES "admin"."task_parameter"("id") ON DELETE CASCADE;


--
-- TOC entry 2231 (class 2606 OID 462552)
-- Name: user_x_role_role_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."user_x_role"
    ADD CONSTRAINT user_x_role_role_fk FOREIGN KEY ("role") REFERENCES "admin"."role"("name") ON DELETE CASCADE;


--
-- TOC entry 2230 (class 2606 OID 462547)
-- Name: user_x_role_user_id_fk; Type: FK CONSTRAINT; Schema: admin; Owner: -
--

ALTER TABLE  "admin"."user_x_role"
    ADD CONSTRAINT user_x_role_user_id_fk FOREIGN KEY ("user_id") REFERENCES "admin"."cstl_user"("id") ON DELETE CASCADE;


-- Completed on 2015-08-26 16:02:15 CEST

--
-- PostgreSQL database dump complete
--

