ALTER TABLE "admin"."sensor" DROP COLUMN "metadata";

CREATE SEQUENCE "admin"."internal_sensor_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE "admin"."internal_sensor" (
    "id" integer GENERATED BY DEFAULT AS SEQUENCE "admin"."internal_sensor_id_seq" NOT NULL,
    "sensor_id" character varying(100) NOT NULL,
    "metadata" text NOT NULL
);

ALTER TABLE "admin"."internal_sensor" ADD CONSTRAINT internal_sensor_id_fk FOREIGN KEY ("id") REFERENCES "admin"."sensor" ("id") ON DELETE CASCADE;

ALTER TABLE "admin"."internal_sensor" ADD CONSTRAINT internal_sensor_pk PRIMARY KEY ("id");

--ALTER TABLE "admin"."internal_sensor" ALTER COLUMN "id" SET DEFAULT nextval('internal_sensor_id_seq'::regclass);