apiVersion: v1
kind: Service
metadata:
  labels:
    service: examind-dbpostgis
  name: examind-dbpostgis
spec:
  ports:
  - name: "postgis"
    port: 5432
    targetPort: 5432
  selector:
    service: examind-dbpostgis
