allInOne:
  ingress:
    path: /examind
    hosts:
      - first.geomatys.com
      - second.geomatys.com
    tls:
      - secretName: my-tls-secret
        hosts:
          - first.geomatys.com
          - second.geomatys.com