springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.config-url=/examind/API/api-docs/swagger-config
springdoc.swagger-ui.url=/examind/API/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.resolve-schema-properties=true
